name: Generate feeds and posts

on:
  workflow_dispatch:
  push:
    paths:
      - 'blogs.csv'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Generate feeds
      run: |
        go mod tidy
        go run feeds.go
    
    - name: Generate posts
      run: |
        go run posts.go
      
    - name: Add, commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add feed.rss
        git add feed.json
        git commit -m "Generate feeds"
        git add .
        git commit -m "Generate posts"
        git push
